update docs to point to latest release by default

diff --git a/docs-gen/Makefile b/docs-gen/Makefile
--- a/docs-gen/Makefile
+++ b/docs-gen/Makefile
@@ -16,8 +16,21 @@ install-npm-dependencies: ## Install npm dependencies
 	npm install
 
 archive-version: ## Archive a version of the documentation. Requires VERSION to be set, e.g. make archive-version VERSION=v0.6.0
+	# Check if version param is set
 	@if [ -z ${VERSION} ]; then \
 		echo "You must specify the version of the docs you want to archive by setting VERSION=<new_version>, e.g. VERSION=v0.6.0"; \
+		exit 1; \
+	fi
+
+	# Check if version is in the correct format
+	@if ! echo "$(VERSION)" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$$'; then \
+		echo "Invalid version: $(VERSION). Expected format: vMAJOR.MINOR.PATCH"; \
+		exit 1; \
+	fi
+
+	# Check if version already exists
+	@if [ -d "content/versions/${VERSION}" ]; then \
+		echo "Version already exists for ${VERSION}"; \
 		exit 1; \
 	fi
 
@@ -37,3 +50,8 @@ archive-version: ## Archive a version of the documentation. Requires VERSION to 
 
 	# Update the quickstart Makefile to include with correct path
 	sed -i '' 's|../../../../|../../../../../|g' includes/versions/${VERSION}/quickstart/Makefile
+
+	# Update the links to point to latest version
+	sed -i '' -E 's|href="versions/v[0-9]+\.[0-9]+\.[0-9]+"|href="versions/${VERSION}"|g' content/_index.md
+	sed -i '' -E 's|latest_stable_version = "/v[0-9]+\.[0-9]+\.[0-9]+"|latest_stable_version = "${VERSION}"|g' hugo.toml
+	sed -i '' -E 's|url = "/versions/v[0-9]+\.[0-9]+\.[0-9]+"|url = "/versions/${VERSION}"|g' hugo.toml
